# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ofstd_tests dcm2xml dcmconv dcmcrle dcmdrle dcmdump dcmftest dcmgpdir dump2dcm xml2dcm stl2dcm pdf2dcm dcm2pdf img2dcm dcm2json cda2dcm dcmodify dcmdata_tests dcmrecv dcmsend echoscu findscu getscu movescu storescp storescu termscu dcmnet_tests dcmiod_tests ofstd oflog dcmdata i2d dcmnet dcmiod)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ofstd_tests
add_executable(ofstd_tests IMPORTED)

# Create imported target dcm2xml
add_executable(dcm2xml IMPORTED)

# Create imported target dcmconv
add_executable(dcmconv IMPORTED)

# Create imported target dcmcrle
add_executable(dcmcrle IMPORTED)

# Create imported target dcmdrle
add_executable(dcmdrle IMPORTED)

# Create imported target dcmdump
add_executable(dcmdump IMPORTED)

# Create imported target dcmftest
add_executable(dcmftest IMPORTED)

# Create imported target dcmgpdir
add_executable(dcmgpdir IMPORTED)

# Create imported target dump2dcm
add_executable(dump2dcm IMPORTED)

# Create imported target xml2dcm
add_executable(xml2dcm IMPORTED)

# Create imported target stl2dcm
add_executable(stl2dcm IMPORTED)

# Create imported target pdf2dcm
add_executable(pdf2dcm IMPORTED)

# Create imported target dcm2pdf
add_executable(dcm2pdf IMPORTED)

# Create imported target img2dcm
add_executable(img2dcm IMPORTED)

# Create imported target dcm2json
add_executable(dcm2json IMPORTED)

# Create imported target cda2dcm
add_executable(cda2dcm IMPORTED)

# Create imported target dcmodify
add_executable(dcmodify IMPORTED)

# Create imported target dcmdata_tests
add_executable(dcmdata_tests IMPORTED)

# Create imported target dcmrecv
add_executable(dcmrecv IMPORTED)

# Create imported target dcmsend
add_executable(dcmsend IMPORTED)

# Create imported target echoscu
add_executable(echoscu IMPORTED)

# Create imported target findscu
add_executable(findscu IMPORTED)

# Create imported target getscu
add_executable(getscu IMPORTED)

# Create imported target movescu
add_executable(movescu IMPORTED)

# Create imported target storescp
add_executable(storescp IMPORTED)

# Create imported target storescu
add_executable(storescu IMPORTED)

# Create imported target termscu
add_executable(termscu IMPORTED)

# Create imported target dcmnet_tests
add_executable(dcmnet_tests IMPORTED)

# Create imported target dcmiod_tests
add_executable(dcmiod_tests IMPORTED)

# Create imported target ofstd
add_library(ofstd STATIC IMPORTED)

# Create imported target oflog
add_library(oflog STATIC IMPORTED)

# Create imported target dcmdata
add_library(dcmdata STATIC IMPORTED)

# Create imported target i2d
add_library(i2d STATIC IMPORTED)

# Create imported target dcmnet
add_library(dcmnet STATIC IMPORTED)

# Create imported target dcmiod
add_library(dcmiod STATIC IMPORTED)

# Import target "ofstd_tests" for configuration "Release"
set_property(TARGET ofstd_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ofstd_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/ofstd_tests"
  )

# Import target "dcm2xml" for configuration "Release"
set_property(TARGET dcm2xml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcm2xml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcm2xml"
  )

# Import target "dcmconv" for configuration "Release"
set_property(TARGET dcmconv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmconv PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmconv"
  )

# Import target "dcmcrle" for configuration "Release"
set_property(TARGET dcmcrle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmcrle PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmcrle"
  )

# Import target "dcmdrle" for configuration "Release"
set_property(TARGET dcmdrle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdrle PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdrle"
  )

# Import target "dcmdump" for configuration "Release"
set_property(TARGET dcmdump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdump PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdump"
  )

# Import target "dcmftest" for configuration "Release"
set_property(TARGET dcmftest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmftest PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmftest"
  )

# Import target "dcmgpdir" for configuration "Release"
set_property(TARGET dcmgpdir APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmgpdir PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmgpdir"
  )

# Import target "dump2dcm" for configuration "Release"
set_property(TARGET dump2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dump2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dump2dcm"
  )

# Import target "xml2dcm" for configuration "Release"
set_property(TARGET xml2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(xml2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/xml2dcm"
  )

# Import target "stl2dcm" for configuration "Release"
set_property(TARGET stl2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(stl2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/stl2dcm"
  )

# Import target "pdf2dcm" for configuration "Release"
set_property(TARGET pdf2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(pdf2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/pdf2dcm"
  )

# Import target "dcm2pdf" for configuration "Release"
set_property(TARGET dcm2pdf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcm2pdf PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcm2pdf"
  )

# Import target "img2dcm" for configuration "Release"
set_property(TARGET img2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(img2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/img2dcm"
  )

# Import target "dcm2json" for configuration "Release"
set_property(TARGET dcm2json APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcm2json PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcm2json"
  )

# Import target "cda2dcm" for configuration "Release"
set_property(TARGET cda2dcm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cda2dcm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/cda2dcm"
  )

# Import target "dcmodify" for configuration "Release"
set_property(TARGET dcmodify APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmodify PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmodify"
  )

# Import target "dcmdata_tests" for configuration "Release"
set_property(TARGET dcmdata_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdata_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests"
  )

# Import target "dcmrecv" for configuration "Release"
set_property(TARGET dcmrecv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmrecv PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmrecv"
  )

# Import target "dcmsend" for configuration "Release"
set_property(TARGET dcmsend APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmsend PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmsend"
  )

# Import target "echoscu" for configuration "Release"
set_property(TARGET echoscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(echoscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/echoscu"
  )

# Import target "findscu" for configuration "Release"
set_property(TARGET findscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(findscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/findscu"
  )

# Import target "getscu" for configuration "Release"
set_property(TARGET getscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(getscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/getscu"
  )

# Import target "movescu" for configuration "Release"
set_property(TARGET movescu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(movescu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/movescu"
  )

# Import target "storescp" for configuration "Release"
set_property(TARGET storescp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(storescp PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/storescp"
  )

# Import target "storescu" for configuration "Release"
set_property(TARGET storescu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(storescu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/storescu"
  )

# Import target "termscu" for configuration "Release"
set_property(TARGET termscu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(termscu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/termscu"
  )

# Import target "dcmnet_tests" for configuration "Release"
set_property(TARGET dcmnet_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmnet_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmnet_tests"
  )

# Import target "dcmiod_tests" for configuration "Release"
set_property(TARGET dcmiod_tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmiod_tests PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmiod_tests"
  )

# Import target "ofstd" for configuration "Release"
set_property(TARGET ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ofstd PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/lib/Release/libofstd.a"
  )

# Import target "oflog" for configuration "Release"
set_property(TARGET oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(oflog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd"
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/lib/Release/liboflog.a"
  )

# Import target "dcmdata" for configuration "Release"
set_property(TARGET dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmdata PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;/usr/lib/libz.dylib"
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/lib/Release/libdcmdata.a"
  )

# Import target "i2d" for configuration "Release"
set_property(TARGET i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(i2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmdata"
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/lib/Release/libi2d.a"
  )

# Import target "dcmnet" for configuration "Release"
set_property(TARGET dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmnet PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ofstd;oflog;dcmdata"
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/lib/Release/libdcmnet.a"
  )

# Import target "dcmiod" for configuration "Release"
set_property(TARGET dcmiod APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dcmiod PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dcmdata;ofstd;oflog"
  IMPORTED_LOCATION_RELEASE "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/lib/Release/libdcmiod.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
