# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmnet/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmnet/apps/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmnet/docs/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmnet/etc/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmnet/include/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmnet/libsrc/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmnet/tests/CMakeLists.txt))

/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4 -B/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode
