# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/oflog/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/oflog/etc/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/oflog/include/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/oflog/libsrc/CMakeLists.txt))

/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4 -B/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode
