# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/apps/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/data/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/docs/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/include/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/libi2d/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/libsrc/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt))

/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4 -B/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode
