# CMake generated Testfile for 
# Source directory: /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests
# Build directory: /Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/dcmdata/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_partialElementAccess "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_partialElementAccess" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_partialElementAccess PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_partialElementAccess NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_i2d_bmp "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_i2d_bmp" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_i2d_bmp PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_i2d_bmp NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_checkStringValue "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_checkStringValue" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_checkStringValue PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_checkStringValue NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_determineVM "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_determineVM" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_determineVM PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_determineVM NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_getValueFromString "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_getValueFromString" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_getValueFromString PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_getValueFromString NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_pathAccess "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_pathAccess" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_pathAccess PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_pathAccess NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_dateTime "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_dateTime" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_dateTime PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_dateTime NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_decimalString_1 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_decimalString_1" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_decimalString_1 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_decimalString_1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_decimalString_2 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_decimalString_2" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_decimalString_2 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_decimalString_2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_decimalString_3 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_decimalString_3" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_decimalString_3 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_decimalString_3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_decimalString_4 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_decimalString_4" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_decimalString_4 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_decimalString_4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_floatingPointDouble "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_floatingPointDouble" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_floatingPointDouble PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_floatingPointDouble NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_personName "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_personName" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_personName PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_personName NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_uniqueIdentifier_1 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_uniqueIdentifier_1" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_uniqueIdentifier_1 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_uniqueIdentifier_1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_uniqueIdentifier_2 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_uniqueIdentifier_2" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_uniqueIdentifier_2 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_uniqueIdentifier_2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_otherLong "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_otherLong" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_otherLong PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_otherLong NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_VRCompare "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_VRCompare" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_VRCompare PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_VRCompare NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_AE "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_AE" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_AE PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_AE NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_AS "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_AS" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_AS PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_AS NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_AT "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_AT" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_AT PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_AT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_CS "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_CS" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_CS PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_CS NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_DA "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_DA" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_DA PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_DA NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_DS "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_DS" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_DS PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_DS NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_DT "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_DT" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_DT PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_DT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_FD "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_FD" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_FD PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_FD NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_FL "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_FL" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_FL PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_FL NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_IS "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_IS" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_IS PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_IS NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_LO "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_LO" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_LO PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_LO NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_LT "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_LT" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_LT PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_LT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_OB "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_OB" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_OB PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_OB NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_OD "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_OD" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_OD PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_OD NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_OF "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_OF" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_OF PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_OF NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_OL "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_OL" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_OL PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_OL NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_OW "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_OW" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_OW PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_OW NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_OverlayData "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_OverlayData" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_OverlayData PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_OverlayData NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_PN "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_PN" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_PN PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_PN NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_PixelData "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_PixelData" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_PixelData PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_PixelData NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_SH "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_SH" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_SH PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_SH NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_SL "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_SL" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_SL PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_SL NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_SQ "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_SQ" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_SQ PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_SQ NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_SS "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_SS" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_SS PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_SS NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_ST "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_ST" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_ST PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_ST NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_TM "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_TM" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_TM PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_TM NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_UC "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_UC" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_UC PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_UC NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_UI "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_UI" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_UI PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_UI NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_UL "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_UL" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_UL PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_UL NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_UN "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_UN" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_UN PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_UN NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_UNKNOWN "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_UNKNOWN" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_UNKNOWN PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_UNKNOWN NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_UNKNOWN2B "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_UNKNOWN2B" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_UNKNOWN2B PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_UNKNOWN2B NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_UR "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_UR" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_UR PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_UR NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_US "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_US" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_US PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_US NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_UT "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_UT" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_UT PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_UT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_lt "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_lt" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_lt PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_lt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_na "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_na" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_na PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_na NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_ox "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_ox" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_ox PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_ox NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_up "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_up" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_up PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_up NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_EVR_xs "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_EVR_xs" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_EVR_xs PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_EVR_xs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_pixelItem "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_pixelItem" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_pixelItem PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_pixelItem NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementLength_pixelSequence "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementLength_pixelSequence" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementLength_pixelSequence PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementLength_pixelSequence NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_elementParent "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_elementParent" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_elementParent PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_elementParent NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_missingDelimitationItems "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_missingDelimitationItems" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_missingDelimitationItems PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_missingDelimitationItems NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_missingSequenceDelimitationItem_1 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_missingSequenceDelimitationItem_1" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_missingSequenceDelimitationItem_1 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_missingSequenceDelimitationItem_1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_missingSequenceDelimitationItem_2 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_missingSequenceDelimitationItem_2" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_missingSequenceDelimitationItem_2 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_missingSequenceDelimitationItem_2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_wrongDelimitationItemForSequence "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_wrongDelimitationItemForSequence" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_wrongDelimitationItemForSequence PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_wrongDelimitationItemForSequence NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_wrongDelimitationItemForItem "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_wrongDelimitationItemForItem" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_wrongDelimitationItemForItem PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_wrongDelimitationItemForItem NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_explicitItemLengthTooLarge "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_explicitItemLengthTooLarge" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_explicitItemLengthTooLarge PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_explicitItemLengthTooLarge NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_oddLengthPartialValue_lastItem "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_oddLengthPartialValue_lastItem" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_oddLengthPartialValue_lastItem PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_oddLengthPartialValue_lastItem NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_oddLengthPartialValue_notLastItem "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_oddLengthPartialValue_notLastItem" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_oddLengthPartialValue_notLastItem PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_oddLengthPartialValue_notLastItem NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_wrongExplicitVRinDataset_default "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_wrongExplicitVRinDataset_default" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_wrongExplicitVRinDataset_default PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_wrongExplicitVRinDataset_default NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_wrongExplicitVRinDataset_defaultVR_dictLen "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_wrongExplicitVRinDataset_defaultVR_dictLen" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_wrongExplicitVRinDataset_defaultVR_dictLen PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_wrongExplicitVRinDataset_defaultVR_dictLen NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_wrongExplicitVRinDataset_dictVR_defaultLen "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_wrongExplicitVRinDataset_dictVR_defaultLen" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_wrongExplicitVRinDataset_dictVR_defaultLen PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_wrongExplicitVRinDataset_dictVR_defaultLen NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_wrongExplicitVRinDataset_preferDataDict "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_wrongExplicitVRinDataset_preferDataDict" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_wrongExplicitVRinDataset_preferDataDict PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_wrongExplicitVRinDataset_preferDataDict NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_parser_undefinedLengthUNSequence "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_parser_undefinedLengthUNSequence" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_parser_undefinedLengthUNSequence PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_parser_undefinedLengthUNSequence NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_readingDataDictionary "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_readingDataDictionary" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_readingDataDictionary PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_readingDataDictionary NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_usingDataDictionary "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_usingDataDictionary" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_usingDataDictionary PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_usingDataDictionary NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_specificCharacterSet_1 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_specificCharacterSet_1" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_specificCharacterSet_1 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_specificCharacterSet_1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_specificCharacterSet_2 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_specificCharacterSet_2" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_specificCharacterSet_2 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_specificCharacterSet_2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_specificCharacterSet_3 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_specificCharacterSet_3" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_specificCharacterSet_3 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_specificCharacterSet_3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_specificCharacterSet_4 "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_specificCharacterSet_4" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_specificCharacterSet_4 PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_specificCharacterSet_4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_attribute_filter "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_attribute_filter" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_attribute_filter PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_attribute_filter NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_attribute_matching "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_attribute_matching" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_attribute_matching PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_attribute_matching NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_newDicomElementPrivate "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_newDicomElementPrivate" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_newDicomElementPrivate PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_newDicomElementPrivate NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dcmdata_generateUniqueIdentifier "/Applications/CMake.app/Contents/bin/cmake" "-DDCMTK_CTEST_TESTCASE_COMMAND=/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" "-DDCMTK_CTEST_TEST_NAME=dcmdata_generateUniqueIdentifier" "-P" "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/CMakeFiles/dcmtkCTestRun.cmake")
  set_tests_properties(dcmdata_generateUniqueIdentifier PROPERTIES  LABELS "dcmdata" REQUIRED_FILES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/xcode/bin/Release/dcmdata_tests" _BACKTRACE_TRIPLES "/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/CMake/dcmtkMacros.cmake;31;add_test;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;8;DCMTK_ADD_TESTS;/Users/mrq/Desktop/works/dcmtk/dcmtk-3.6.4/dcmdata/tests/CMakeLists.txt;0;")
else()
  add_test(dcmdata_generateUniqueIdentifier NOT_AVAILABLE)
endif()
